#### Imports

In [27]:
## importar as bibliotecas básicas

import numpy as np
import pandas as pd
import random

## for plotting
import matplotlib.pyplot as plt
import seaborn as sns
    
## plot style and warnings    
plt.style.use('ggplot')
from IPython.display import display # Allows the use of display() for DataFrames
import warnings
warnings.filterwarnings('ignore')

### Abertura da Base de Dados

In [28]:
df = pd.read_csv('data/atpchina.csv', sep=',')

# **Data Understanding**

No primeiro notebook, criou-se um novo csv (atpchina) com todos os jogos jogados na China.

Neste subcapítulo, vamos ver todas as variáveis existentes e verificar que tipo de erros podem existir (sejam nulos ou valores que não fazem sentido, outliers, etc), para depois no Data Preparation estarmos preparados para lidar com esses valores.

### Informaçãoes sobre a base de dados

In [29]:
df.head(6)

,PlayerName,Born,Height,Hand,LinkPlayer,Tournament,Date,Ground,Prize,GameRound,GameRank,Oponent,WL,Score,Location
0,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,ATP Masters 1000 Shanghai,2019.10.07 - 2019.10.13,Hard,"$7,473,620",Round of 64,NaN,bye,NaN,NaN,China
1,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,ATP Masters 1000 Shanghai,2019.10.07 - 2019.10.13,Hard,"$7,473,620",Quarter-Finals,7,Stefanos Tsitsipas,L,63 57 36,China
2,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,ATP Masters 1000 Shanghai,2019.10.07 - 2019.10.13,Hard,"$7,473,620",Round of 32,36,Denis Shapovalov,W,63 63,China
3,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,ATP Masters 1000 Shanghai,2019.10.07 - 2019.10.13,Hard,"$7,473,620",Round of 16,17,John Isner,W,75 63,China
4,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,ATP Masters 1000 Shanghai,2018.10.08 - 2018.10.14,Hard,"$7,086,700",Finals,19,Borna Coric,W,63 64,China
5,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,ATP Masters 1000 Shanghai,2018.10.08 - 2018.10.14,Hard,"$7,086,700",Quarter-Finals,8,Kevin Anderson,W,"76, 63",China

In [30]:
df.shape

(26357, 15)

In [5]:
df.columns

Index(['PlayerName', 'Born', 'Height', 'Hand', 'LinkPlayer', 'Tournament',
       'Date', 'Ground', 'Prize', 'GameRound', 'GameRank', 'Oponent', 'WL',
       'Score', 'Location'],
      dtype='object')

In [6]:
print(df.dtypes)

PlayerName     object
Born           object
Height        float64
Hand           object
LinkPlayer     object
Tournament     object
Date           object
Ground         object
Prize          object
GameRound      object
GameRank       object
Oponent        object
WL             object
Score          object
Location       object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26357 entries, 0 to 26356
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PlayerName  26357 non-null  object
 1   Born        21043 non-null  object
 2   Height      21016 non-null  float64
 3   Hand        23475 non-null  object
 4   LinkPlayer  26357 non-null  object
 5   Tournament  26357 non-null  object
 6   Date        26357 non-null  object
 7   Ground      26357 non-null  object
 8   Prize       25872 non-null  object
 9   GameRound   26357 non-null  object
 10  GameRank    25707 non-null  object
 11  Oponent     26357 non-null  object
 12  WL          25707 non-null  object
 13  Score       25705 non-null  object
 14  Location    26357 non-null  object
dtypes: float64(1), object(14)
memory usage: 3.0+ MB

In [8]:
df.describe()

             Height
count  21016.000000
mean     182.650742
std       12.181615
min        0.000000
25%      178.000000
50%      183.000000
75%      188.000000
max      211.000000

Nota: Já é percetível que aquele outlier não existe nesta nova base de dados. Mas teremos que verificar o jogador com 211 cm.

### Valores Omissos

Em baixo vamos verificar o número de omissos para cada variável.

In [9]:
nan_count2 = df.isna().sum()
print(nan_count2)

PlayerName       0
Born          5314
Height        5341
Hand          2882
LinkPlayer       0
Tournament       0
Date             0
Ground           0
Prize          485
GameRound        0
GameRank       650
Oponent          0
WL             650
Score          652
Location         0
dtype: int64

Como a variável target é a Score (não é bem essa variável, vai ser sim, uma variável nova que vai ser construída a partir da score), não poderão existir valores nulos nesta variável. 

Portanto, estas 652 observações da variável Score deverão ser apagadas.

Em relação às variáveis GameRank, WL e Score a sensação que dá, é que se apagarmos as 652 observações associadas aos omissos, nas restantes duas variáveis mencionadas, também deverão ficar sem omissos. 

Então, o próximo código que deveremos realizar terá que nos dar a possibilidade de verificar em que observações existem NA's.

De resto, podemos concluir, que nas colunas PlayerName, LinkPlayer, Tournament, Date, Ground, GameRound, Oponent e Location não existem omissos.

##### Verifcação de alguns omissos

In [10]:
num_rows_with_na_in_both = df[['WL', 'Score', 'GameRank']].isna().all(axis=1).sum()

print(num_rows_with_na_in_both)

650

Como é possível concluir acima, nas 650 observações onde existem omissos de GameRank e WL também existem NA's em Score. 

Portanto, quando formos apagar essas 652 observações de omissos da variável score, os 650 omissos de GameRank e WL também serão apagados.

### Valores únicos

Será importante perceber os valores únicos existentes dentro da nossa base de dados.

#### Variável Tournament

In [11]:
print(df['Tournament'].unique())

['ATP Masters 1000 Shanghai' 'Beijing' 'Tennis Masters Cup'
 'Beijing Olympics' 'Kaohsiung' 'Shanghai' 'Nanchang' 'Shenzhen' 'Zhuhai'
 'Chengdu' 'Quanzhou' 'Anning' 'Qingdao' 'Ningbo' 'Qujing' 'Shenzhen 2'
 'Suzhou' 'Guangzhou' 'Chinese Taipei F2' 'Taipei' 'China F4' 'China F3'
 'Zhangjiagang' 'Jinan' 'China F5' 'Liuzhou' 'China F9' 'China F8'
 'China F7' 'Kun-Ming' 'An-Ning' 'China F2' 'Baotou' 'China F6'
 'AOG1 CHN vs KOR Round 1' 'Hong Kong F4' 'Pingguo' 'Shanghai1'
 'Chinese Taipei F1' 'China F1' 'Nanjing'
 'CHN vs. JPN DC Qualifier 1st Round' 'Hong Kong' 'China F14' 'Wuhan'
 'Hong Kong F5' 'Chinese Taipei F3' 'CHN vs. KAZ AOG I 2nd RD'
 'TPE vs. KAZ AOG I 1st RD' 'CHN vs. IND AOG1 2nd Round'
 'TPE vs. IRN AOG2 Play-Off' 'AOG1 TPE vs. CHN 1st Round' 'Tianjin'
 'CHN v. JPN AOG1 1st Rd' 'China F11' 'China F10' 'Wuhai'
 'CHN vs. UZB AOGI 2nd Rd.' 'CHN vs. UZB AOG I 1st RD' 'China F12'
 'China F13' 'CHN vs. AUS AOG 1 2nd RD' 'M25 Taipei' 'M25 Shenzhen'
 'M25 Luan' 'M25 Wuhan' 'TPE vs. AUS AOGI 1st Rd.' 'M25 Qujing'
 'M25 Yinchuan' 'M25 Hengyang' 'M25 Luzhou' 'M15 Anning' 'M15 Wuhan'
 'M25 Kunshan' 'Chinese Taipei F4' 'Hong Kong F2'
 'TPE vs. KOR AOGI 1st Rd. Play-Off' 'TPE vs. PHI AOGII 2nd Rd.'
 'TPE vs. LIB AOGII 1st RD' 'CHN vs. TPE AOGI 1st RD'
 'TPE vs. IND AOG I 2nd RD' 'TPE vs. AUS AOGI 1st. RD'
 'TPE v. CHN AOGI 1st Rd PO' 'TPE v. HKG AOGII 3rd RD'
 'CHN v. TPE AOGII 2nd RD' 'TPE v. KAZ AOGII' 'CHN vs. LIB AOGII 1st. RD'
 'M15 Nanchang' 'CHN vs TPE AOGI Play-off'
 'TPE vs. CHN AOG1 Play-off 1st Rd' 'TPE vs. PHI AOG I Play-Offs'
 'AOG1 CHN vs. NZL 1st Round' 'CHN vs. NZL AOGI 1st Rd.'
 'CHN vs. THA AOG I 3rd RD Play-off' 'G2 BEN vs HKG Round 1'
 'TPE vs. INA AOGI 2nd Rd. Play-Off' 'Chines Taipei F3'
 'TPE v. THA AOG1 1st Rd' 'TPE v. PAK AOGI 1st RD'
 'TPE v. KOR AOGI 2nd Rd.' 'TPE v. UZB AOG1 1st RD' 'Taipei F1'
 'CHN v. PAK AOGI 2nd Rd. PO' 'TPE vs. MAS AOG2 1st RD'
 'CHN v. KUW AOGII 2nd Rd.' 'THA V CHN AOG1' 'KOR V CHN AOG1'
 'CHN v KUW AOZ2 Rd 1' 'CHN v. INA AOGI 2nd RD PO' 'CHN v. PHI AOGII'
 'NZL V CHN AOZ1' 'IND v CHN AOGI Rd 1' 'UZB V CHN AZO1' 'UZB V CHN AOG1'
 'JPN V CHN AZ1' 'INO V CHN AOZ' 'Canton' 'NZL V CHN EZF']

#### Variável Score

Na variável Score, é percetível reparar que existem algumas deformações no Score

In [12]:
(df["Score"].unique())

array(['63 57 36', '75 63', '63 63', ..., '16 64 41 (RET)', '64 16 8-10',
       '61 67 16'], dtype=object)

#### Variável Born

Nesta variável deverá ser aplicado a mesma lógica usada no último notebook para a variável Location. Usamos o Split[-1] para obter a última observação e ficamos com os países unicamente.

Muito possivelmente, existirão casos em que ficaremos apenas com as cidades dos jogadores e aí deveremos fazer a imputação da cidade para o país onde o jogador nasceu.

Mais tarde para ser possível, colocar esta variável no modelo, deverá-se juntar os países de cada continente e depois criar dummies.

In [13]:
print(df['Born'].unique())

['Belgrade, Serbia' 'Moscow, Russia' 'Manacor, Mallorca, Spain'
 'Hamburg, Germany' 'Athens, Greece' 'Rome, Italy' 'Oslo, Norway'
 'Montreal, Canada' 'Wroclaw, Poland' 'Johannesburg, South Africa'
 'Rancho Santa Fe, CA, USA' 'Tel Aviv, Israel' 'Buenos Aires, Argentina'
 'Castellon de la Plana, Spain' 'St. Joseph, MI, USA' 'Gijon, Spain'
 'Tbilisi, Georgia' 'Turin, Italy' 'Greensboro, NC, USA'
 'Medjugorje, Bosnia-Herzegovina' 'Paris, France' 'Basel, Switzerland'
 'Birmingham, England' 'Sydney, Australia' 'Haskovo, Bulgaria'
 'Santiago, Chile' 'Hyattsville, MD, USA' 'Gatchina, Russia'
 'Sanremo, Italy' 'Barcelona, Spain' 'Azul, Argentina' 'Sombor, Serbia'
 'Minsk, Belarus' 'Cape Town, South Africa' 'Alzira, Spain'
 'Avignon, France' 'Wiener Neustadt, Austria' 'Shimane, Japan'
 'Thousand Oaks, CA, USA' 'Senta, Serbia' 'Piedmont, CA, USA'
 'Nyiregyhaza, Hungary' 'Warstein, Germany' 'Sangju, South Korea'
 'Furtwangen, Germany' 'Cuenca, Spain' 'Kempen, Germany'
 'Rocourt, Belgium' 'Helsinki, Finland' 'Brisbane, Australia'
 'Cologne, Germany' 'Piotrkow Trybunalski, Poland'
 'Pribram, Czech Republic' 'Tenerife, Spain' 'Beziers, France'
 'Guimaraes, Portugal' 'Skovde, Sweden' 'Kiev, Ukraine' 'Lohja, Finland'
 'Vilnius, Lithuania' 'Santanyi, Mallorca, Spain' 'Palermo, Italy'
 'Mie, Japan' 'Adelaide, Australia' 'Munich, Germany'
 'Bahia Blanca, Argentina' 'Canberra, Australia' 'Concordia, Argentina'
 'New York, NY, USA' 'Orange, CA, USA' 'Karlsruhe, Germany'
 'San Francisco, CA, USA' 'Galanta, Slovakia' 'Toledo, Spain'
 'Bondy, France' 'Fortaleza, Brazil' 'Chisinau, Moldova'
 'Skopje, Macedonia' 'Stockport, England' 'Madrid, Spain'
 'Mulheim an der Ruhr, Germany' 'Bratislava, Slovakia' 'Augsburg, Germany'
 'Jesus Maria, Argentina' 'Skara, Sweden' 'Vernon, Canada'
 'Schiltigheim, France' 'Grande-Synthe, France'
 'Sarajevo, Bosnia-Herzegovina' 'Bolzano, Italy' 'Nice, France'
 'Ljubljana, Slovenia' 'Podolsk, Russia' 'Lincoln, NE, USA'
 'Taipei, Chinese Taipei' 'Gallatin, TN, USA' 'Montbrison, France'
 'Atlanta, GA, USA' 'Avola, Italy' 'Volgograd, Russia'
 'Fort Worth, TX, USA' 'Zagreb, Croatia' 'Derby, England' 'Chennai, India'
 'Elche, Spain' 'Grottaglie, Italy' 'Podgorica, Montenegro'
 'Roosendaal, The Netherlands' 'Ptuj, Slovenia' 'Zurich, Switzerland'
 'Faenza, Italy' 'Istanbul, Turkey' 'Nuremberg, Germany'
 'Santiago del Estero, Argentina' 'Amanzimtoti, South Africa'
 'Lourinha, Portugal' 'Pau, France' 'Naples, Italy' 'Piestany, Slovakia'
 'Torrance, CA, USA' 'Muehlacker, Germany' 'Bueckeburg, Germany'
 'Le Mans, France' 'Budapest, Hungary' 'Bell Ville, Argentina'
 'Sendai, Japan' 'Lausanne, Switzerland' 'Sapporo, Japan' 'Creil, France'
 'Toronto, Canada' 'Jhajjar, India' 'Caldas da Rainha, Portugal'
 'Innsbruck, Austria' 'Oostende, Belgium' 'Kanagawa, Japan'
 'Dneprodzerzhinsk, Ukraine' 'Arad, Romania' 'Tokyo, Japan'
 'The Hague, The Netherlands' 'Porto, Portugal' 'Lisbon, Portugal'
 'Saitama, Japan' 'Brno, Czech Republic' nan 'Torre del Greco, Italy'
 'Almeria, Spain' 'Pontivy, France' 'Orenburg, Russia'
 'Busto Arsizio, Italy' 'Thiais, France' 'Taichung, Chinese Taipei'
 'Genk, Belgium' 'Shanghai, China' 'Stuttgart, Germany' 'Riga, Latvia'
 'Pilsen' 'Corrientes, Argentina' 'Orkdal, Norway' 'Mokrin, Serbia'
 'Antwerp, Belgium' 'Almaty' 'Hostalric, Spain' 'Bizerte, Tunisia'
 'Mestre-Venice, Italy' 'Changhwa' 'Durban, South Africa' 'Gatchina'
 'Seoul, South Korea' 'Kiryat Shmonna, Israel' 'Poway, CA, USA'
 'North Vancouver, Canada' 'Mansoura, Egypt' 'Severodonetsk, Ukraine'
 'Jecheon, South Korea' 'Essen, Germany' 'Monaco' 'Amsterdam, Netherlands'
 'Box Hill' 'Nanjing, China' 'Gifu, Japan' 'Namangan' 'Vienne, France'
 'Santa Fe' 'Stockholm, Sweden' 'St. Petersburg, Russia' 'Cali, Colombia'
 'Busan, South Korea' 'Nova Gradiska, Croatia' 'Gothenburg, Sweden'
 'Madrid' 'Suwon, South Korea' 'La Roda (Albacete), Spain'
 'Fukuoka, Japan' 'Chicago, IL, USA' 'Biella, Italy' 'Kharkiv'
 'Angers, France' 'Hiroshima, Japan' 'Konan, Japan' 'Santo Domingo'
 'Townsville, Australia' 'Shreveport, LA, USA' 'Nimes, France'
 'Preston, Australia' 'Ann Arbor, MI, USA' 'London, England'
 'Ho Chi Minh, Vietnam' 'Paris' 'Gangwonto' 'Bytom, Poland'
 'New Delhi, India' 'Osaka, Japan' 'Bradenton, FL, USA'
 'Melnik, Czech Republic' 'Bruges, Belgium' 'Tianjin, China'
 'Toulouse, France' 'Akashi, Hyogo, Japan' 'Hsinchu, Taiwan'
 'Beijing , China' 'Valencia, Spain' 'Sao Paulo, Brazil' 'Vuyyuru, India'
 'Evian-les-Bains, France' 'Hobart, Australia' 'Liege, Belgium'
 'Pereira, Colombia' 'Locarno, Switzerland' 'Milwaukee, WI, USA'
 'Schoelcher, France' 'Giza, Egypt' 'Seoul, Korea' 'Samarkand, Uzbekistan'
 'Tandil, Argentina' 'Tiete, Brazil' 'San Diego,CA, USA'
 'Barmera, Australia' 'Glendale, USA' 'Westminster, Great Britain'
 'Sacramento, CA, USA' 'Krasnoyarsk, Russia' 'Tampere, Finland'
 'Kumamoto, Japan' 'Alessandria, Italy' 'Melbourne' 'Long Beach, CA, USA'
 'Mostar, Bosnia & Herzegovina' 'Porto Alegre, Brazil' 'Princeton NJ'
 'Coburg, Germany' 'Wuhan, China' 'Taipei' 'Beijing, China'
 'Coimbatore, India' 'Guastalla' 'Bologna, Italy' 'Cittadella, Italy'
 'Tallinn, Estonia' 'Kolkata' 'Las Vegas, NV, USA' 'Tokyo'
 'Deggendorf, Germany' 'Chunghua' 'Hang Zhou, China' 'Osaka Japan'
 'Castel del Piano, Italy' 'Nahodka, Russia' 'Dinan, France' 'Mysore'
 'Sanda, Japan' 'Tianjin' 'Kyoto-Uji, Japan' 'Shizuoka'
 'Klaipeda, Lithuania' 'Lecco, Italy' 'Fukushima' 'Bordeaux, France'
 'Minsk' 'Subotica, Serbia' 'New York' 'CHINA' 'Gisborne, New Zealand'
 'Ishikawa' 'Osaka' 'Santiago, Dominican Republic' 'Tashkent, Uzbekistan'
 'Hefei, China' 'Okayama' 'Secuderabad, India' 'Istanbul' 'Yong-In, Korea'
 'Mogi das Cruzes, Brazil' 'keelung' 'Taichung, Taiwan' 'Busan, Korea'
 'Ostrava, Czech Republic' 'Taizhou, China' 'Delhi, India'
 'Montpellier, France' 'Andong' 'Auckland, New Zealand'
 'Montargis, France' 'Taiwan' 'Banja Luka, Bosnia-Herzegovina'
 'Vienna, Austria' 'Sofia, Bulgaria' 'Spokane' 'Huhehaote, China'
 'Wuxi, China' 'Hondarribia, Guip�zcoa, Spain' 'Nagoya' 'Yerevan'
 'Bangalore, India' 'Gunma, Japan' 'Hangzhou, China' 'Brisbane'
 'Slough, England' 'Washington D.C., USA' 'Hyogo' 'Sibenik, Croatia'
 'Modbury, South Australia' 'Dunkerque' 'Bilbao, Spain' 'Dalian'
 'Gold Coast, Australia' 'Aalst, Belgium' 'Bangkok, Thailand'
 'Xuzhou, China' 'Bratislava' 'T�bingen' 'Ludhiana, India'
 'Izmail, Ukraine' 'Luxembourg City, Luxembourg'
 'Mar del Plata, Argentina' 'Murcia, Spain' 'Bourg-en-Bresse, France'
 'Bayreuth, Germany' 'Lodz, Poland' 'Karvina, Czech Republic'
 'Narrandera, Australia' 'Alicante, Spain' 'Dublin, Ireland'
 'Strasbourg, France' 'Caringbah, Australia' 'Williamstown, Australia'
 'Denver, CO, USA' 'Tampa, FL, USA' 'Merzig, Germany' 'Jesenice, Slovenia'
 'Yekaterinburg, Russia' 'Marseille, France' 'Rehovot, Israel'
 'Ludwigsburg, Germany' 'Niagara Falls, Canada' 'Harpenden, England'
 'Nashville, TN, USA' 'Assen, The Netherlands' 'Limerick, Ireland'
 'Jajce, Bosnia-Herzegovina' 'Frankfurt, Germany' 'Jakarta, Indonesia'
 'Suwon' 'Rio de Janeiro, Brazil' 'Prague, Czech Repbulic'
 'Northampton, Great Britain' 'Lyngby, Denmark' 'Chandigarh, India'
 'Nambour, Australia' 'Breno, Italy' 'Palo Alto' 'Greenville, TN, USA'
 'Haarlem, The Netherlands' 'Brescia, Italy' 'Santos, Brazil'
 'Sakai, Japan' 'Saudi Arabia' 'Abymes, Guadeloupe' 'Cagayan de Oro City'
 'Gennevilliers, France' 'Heerenveen, Netherlands' 'AN SUNG'
 'Zwettl, Austria' 'Jeju' 'Bishkek, Kyrgyzstan' 'Turnov, Czech Republic'
 'Prague, Czech Republic' 'Santa Ana' 'Weingarten, Germany'
 'Venice Beach, CA, USA' 'Taiwan, Taipei' 'Xin jiang' 'Kunming, China'
 'HEILONGJIANG' 'Hong Kong' 'Port Lincoln' 'Daejeon' 'San Jose'
 'Okayama, Japan' 'Rijeka, Croatia' 'Leerdam, The Netherlands'
 'Trencin, Slovakia' 'Pretoria' 'Visakhapatnam' 'Geneva, Switzerland'
 'Gojo, Japan' 'Wakayama, Japan' 'Brooklyn, New York' 'Kyoto, Japan'
 'Perth, Australia' 'Hunan' 'Zvolen, Slovak Republic' 'Mumbai, India'
 'Wellington' 'Tver, Russia' 'Fuzhou,China' 'Charleroi, Belgium'
 'Culiacan, Mexico' 'sichuan suining' 'Nantong, China' 'Hunan, China'
 'Masku, Finland' 'Sant Carles de la Rapita' 'Assam, India'
 'Columbus, Ohio, U.S.A.' 'Bucharest, Romania' 'Benevento, Italy'
 'Faro, Portugal' 'Mali Losinj, Croatia' 'Detroit, MI, USA' 'Erice'
 'Boleslawiec, Poland' 'Viriat, France' 'Dornbirn, Austria'
 'Monte Carlo, Monaco' 'Bayonne, France' 'Fort Lauderdale, FL, USA'
 'Split, Croatia' 'Pula, Croatia' 'Almaty, Kazakhstan' 'Tours, France'
 'Aichi, Japan' 'Masterton, New Zealand' 'Sucy En Brie'
 'Queenstown, New Zealand' 'Zevenaar, Netherlands' 'Namur, Belgium'
 'Milan, Italy' 'Feldkirch, Austria' 'Tottori, Japan'
 'Melbourne, Australia' 'Cape Cod, MA, USA' 'Richmond, England'
 'Chrzanow, Poland' 'Edina, Minnesota, USA' 'Haifa, Israel'
 'Orenbourg, Russia' 'Donestk, Ukraine' 'Graz, Austria'
 'Bjelovar, Croatia' 'Hoingsung, Korea' 'Michalovce, Slovakia'
 'Chang Sha, China' 'tianjin' 'Kaifeng, China' 'Badougbe, Togo' 'Tainan'
 'Lima, Peru' 'Rosario, Argentina' 'Singapore' 'Baltimore, Maryland'
 'Severodonezk, Ukraine' 'Yonkers, New York, USA' 'Ottawa, Canada'
 'Cordoba, Argentina' 'Darmstadt, Germany' 'Vic, Barcelona'
 'Vladivostok, Russia' 'Mayen, Germany' 'Glasgow, Scotland'
 'Onteniente, Spain' 'Dax, France' 'Gosford, Australia'
 'Long Beach, California, USA' 'Los Angeles, CA, USA' 'Campinas, Brazil'
 'Jackson, Mississippi, USA' 'Kislovodsk, Russia'
 'Fresno, California, USA' 'Lemgo, Germany' 'Vina del Mar, Chile'
 'Malmo, Sweden' 'Quebec, Canada' 'Torrance, CA, U.S.A.' 'Padova, Italy'
 'Heidelberg, Germany' 'Bandung, Indonesia' 'Lauterach, Austria'
 'Guildford, Great Britain' 'Oklahoma City, OK, USA'
 'Bristol, Great Britain' 'Washington, DC, USA' 'Baden-Baden, Germany'
 'Macerata, Italy' 'Battambang, Camboda' 'Qing Dao, China'
 'Pisek, Czech Republic' 'Correggio, Italy' 'Tibro, Sweden'
 'Omaha, Nebraska, USA' 'Korbach, Germany' 'Passo Fundo, Brazil'
 'Newport Beach, CA, USA' 'Klagenfurt, Austria' 'Warsaw, Poland'
 'Calabasas, CA, USA' 'Asuncion, Paraguay' 'Posadas-Misiones, Argentina'
 'Temperley, Argentina' "King William's Town, RSA"
 'Pontiac, Michigan, USA' 'Kibutz Nahshonin, Israel' 'Concepcion, Chile'
 'Guayaquil, Ecuador' 'Palma de Mallorca, Spain' 'Nevers, France'
 'fukuoka' 'Surabaya, Indonesia' 'Rotterdam, The Netherlands'
 'Schwaz, Austria' 'Domazlice, Czech Republic' 'Ollon, Vaud, Switzerland'
 'Holzminden, Germany' 'Los Angeles, California, USA' 'Waregem, Belgium'
 'Tulsa, OK, U.S.A.' 'Hagen, Germany' 'Montebello, California, USA'
 'Ledec, Czech Republic' 'Spokane, WA, USA' 'Ratchaburi, Thailand'
 'Cannes, France' 'Bonn, Germany' 'Sochi, Russia' 'Chicago, Illinois, USA'
 'Nassau, Bahamas' 'Taipei City' 'Rio Cuarto, Argentina' 'Odense, Denmark'
 'Linkoping, Sweden' 'Vaxjo, Sweden' 'San Francisco (Cordoba), ARG'
 'Boras, Sweden' 'Sliedrecht, The Netherlands'
 'Leiderdorp, The Netherlands' 'Lahore, Pakistan' 'Kolin, Czech Republic'
 'New-Brunswick, Canada' 'kanagawa' 'Chiba, Japan' 'Linlithgow, Scotland'
 'Jiangsu Nanjing, China' 'Rufino, Argentina' 'Amsterdam, The Netherlands'
 'Zwolle, The Netherlands' 'Bahia Blanca' 'Uznach, Switzerland' 'Berlin'
 'Boksburg, South Africa' 'Lugo, Spain' 'Santa Monica, California, USA'
 'Merrick, NY' 'Ramie, Israel' 'Hjorring, Denmark' 'Japan'
 'Koblenz, Germany' 'Wimbledon, England' 'Constanta, Romania'
 'Fiskebackskil, Sweden' 'Florianopolis, Brazil' 'Barquisimeto'
 'Bratislava, Slovak Republic' 'Viareggio, Italy'
 'Mijdrecht, The Netherlands' 'Memmingerberg, Germany' 'Stockholm'
 'Oxford, England' 'Washington, D.C., USA' 'Livingston, New Jersey, USA'
 'Zlin, Czech Republic' 'Melbourne, Victoria, Australia'
 'Adelaide, S.A., Australia' 'Copenhagen, Denmark'
 'Belo Horizonte, Brazil' 'Las Vegas, Nevada, USA' 'Mulheim, Germany'
 'Montreal, Quebec, Canada' 'Milano, Italy'
 'Huntington, West Virginia, USA' 'Altstaetten, Switzerland' 'Hoorn'
 'Norwich' 'Peoria, Illinois, USA' 'Jersey City, NJ, USA'
 'Hitchin, England' 'Lerida, Spain' 'Reading, MA, USA'
 'Casablanca, Morocco' 'Madagascar' 'Dachau, Germany'
 'Decin, Czech Republic' 'Los Angeles, CA, U.S.A.' 'Bangkok'
 'schwaebisch hall' 'Rabat, Morocco' 'Turku, Finland' 'Sora, Italy'
 'Yerevan, Armenia' 'Weert, The Netherlands' 'Bratislava, Czechoslovakia'
 'Bern, Switzerland' 'Tijuana, Mexico' 'Dijon, France'
 'Boxmeer, The Netherlands' 'Komsomolsk, Russia' 'Ufa, Russia'
 'Roermond, Netherlands' 'Seoul' 'Brisbane, QLD, Australia'
 'Calcutta, India' 'Olomouc, Czech Republic'
 'Silver Spring, Maryland, USA' 'Yokohama, Japan' 'Dae Gu, Korea'
 'Mountain View, CA, USA' 'Harare, Zimbabwe' 'Conegliano, Veneto, Italy'
 'Highpoint, NC' 'Hamm, Germany' 'Filipstad, Sweden'
 'Hoboken, New Jersey, USA' 'Olofstrom, Sweden' 'Aranjuez, Spain'
 'Grone, Switzerland' 'Acqui Terme, Italy' 'Santa Monica, CA, USA'
 'Lyon, France' 'Constanta' 'Sydney, NSW, Australia' 'Bari, Italy'
 'Bielefeld, Germany' 'Brussels, Belgium' 'Philadelphia, PA, USA'
 'Freeport, Bahamas' 'Wertheim, Germany' 'Mount Isa, QSLD, Australia'
 'Lund, Sweden' 'Knoxville, TN, USA' 'Prerov, Czech Republic'
 'Narrabri, NSW, Australia' 'Liberec, Czech Republic'
 'Manhattan Beach, CA, USA' 'Bloemfontein, South Africa'
 'Amarillo, TX, USA' 'Jonkoping, Sweden' 'Minneapolis, MN' 'Marl, Germany'
 'Mol, Belgium' 'Gympie, Queensland, AUS' 'Kiriat Ono, Israel'
 'Madras, India' 'Tangeren, Belgium' 'Danville, VA, U.S.A.'
 'New South Wales, Australia' 'San Jose, California, USA'
 'Newport Beach, CA, U.S.A.' 'Toowoomba, QSLD, Australia'
 'Windsor, Ontario, Canada' 'Medford, OR, USA' 'Bagnol Sur Ceze, France'
 'St. Ingbert, Germany' 'Peterborough, England' 'Shizuoka, Japan'
 'Christchurch, New Zealand' 'Taipei, Taiwan' 'Sanford, Florida, USA'
 'Eindhoven, Netherlands' 'Caracas, Venezuela' 'Southampton, England'
 'Phoenix, AZ, USA' 'Lagny, France' 'Leverkusen, Germany'
 'Walton-on-Thames, England' 'Goteborg, Sweden' 'St. Louis, MO, USA'
 'Buffalo, NY' 'Provo, UT, USA' 'Auburn, NY' 'Brandys, Czech Republic'
 'Loughton, Essex, England' 'Manhasset, NY' 'Kaliningrad, Russia'
 'Rafaela, Argentina' 'Dedemsvaart, Netherlands'
 "Le Pontet d' Ozon, France" 'Dallas, TX' 'Taby, Sweden'
 'Huntsville, AL, USA' 'Tucson, AZ, USA' 'Vancouver, BC, Canada'
 'Pretoria, South Africa' 'Salto, Uruguay' 'Winter Haven, FL, USA'
 'Radolfzell, Germany' 'Heerde, Netherlands' 'Pacific Palisades, CA'
 'Regensburg, Germany' 'Trinec, Czech Republic' 'Kent, England'
 'Enugu, Nigeria' 'Puttlingen, Germany' 'Hubei, China'
 'Vanersborg, Sweden' 'Naperville, IL' 'Jacksonville, FL'
 'Griffith, NSW, Australia' 'Klausenburg, Rumania' 'Honolulu, HI'
 'Kiangsu, China' 'Inowroclaw, Poland' 'Los Angeles, CA' 'Hoboken, NJ'
 'Toronto, Ontario, Canada' 'Lidkoping, Sweden' 'Solihull, England'
 'Nairobi, Kenya' 'Chicago, IL' 'Goteburg, Sweden'
 'Redcliffe, QSLD, Australia' 'Berlin, Germany' 'Villach, Austria'
 'Belleville, IL, U.S.A.' 'Uitenhage, South Africa'
 'Muar, Johor, Malaysia' 'Gudmundra, Sweden' 'Bronx, NY, USA'
 'Pietermaritzburg, South Africa' 'Arcadia, CA, USA' 'Oakland, CA'
 'Newark, NJ' 'St. Louis, MO' 'Tangier, Morocco' 'Novo Hamburgo, Brazil'
 'Cummins, Australia' 'Vasteras, Sweden' 'Mariestad, Sweden'
 'Symmons, Plains,Tasmania,Aust.' 'Sedan, France'
 'Ostrava, Czechoslovakia' 'Fort Gordon, GA, USA' 'Orizaba, Mexico'
 'Rotterdam, Netherlands' 'Milwaukee, WI' 'Cincinnati, OH'
 'Ulju, South Korea' 'Southampton, NY, USA' 'Manila, Philippines'
 'Gumeracha, Australia' 'Hialeah, FL' 'Santurce, Puerto Rico'
 'Kagoshima, Japan' 'Lagos, Nigeria' 'San Francisco, CA' 'Shelby, NC'
 'Springfield, MA' 'Stanford, CA' 'Mobile, AL' 'Murgon, QLD, Australia'
 'Epsom, Surrey, England' 'Walnut Creek, CA' 'Wellington, New Zealand'
 'Ludwigshafen, Germany' 'New York, NY' 'Boonton, NJ'
 'Redcliffe, Australia' 'Port Au Prince, Haiti' 'Bilovec, Czech Republic'
 'Soisy-sous-Montmorency, France' 'Marbella, Spain' 'New Plymouth'
 'Walnut Creek' 'San Juan de Alicante, Spain'
 'Sarajevo, Bosnia & Herzegovina' 'Malaga, Spain' 'Medellin, Colombia'
 'Alushta, Ukraine' 'Cernusco sul Naviglio, Italy' 'La Spezia, Italy'
 'Murray Bridge, Australia' 'Presov, Slovakia' 'Gold Coast'
 'Ivanovo, Russia' 'Samara' 'Glendale, CA, USA' 'Antalya, Turkey'
 'Bisceglie, Italy' 'Torino, Italy' 'Volzhskij, Russia' 'Tula, Russia'
 'Ogulin, Croatia' 'Le Pont-De-Beauvoisin' 'Pune, India' 'Kiev,Ukraine'
 'Mumbai' 'Vladikavkaz, Russia' 'Grenoble, France'
 'Portschach am Worthersee' 'split' 'S�o Jos� dos campos, Brazil'
 'Umtata, South Africa' 'Les Lilas, France' 'New Taipei City'
 'Dalian, China' 'Wuhan' 'Saipan' 'Redwood City, CA' 'Harare'
 'Bogota, Colombia' 'YOKOHAMA' 'Lincoln, Great Britain' 'Sydney' 'Fargo'
 'Turku' 'Sarajevo' 'Vercelli, Italy' 'Auckland' 'Vincennes, France'
 'Belvedere Marittimo, Italy' 'Atlanta Ga' 'Belgrade' 'Temirtau'
 'Shanghai' 'Yokohama' 'Dniepropetrovsk, Ukraine'
 'Usti Nad Labem, Czech Republic' 'Saint-Germain-En-Laye, France'
 'Hyogo, Japan' 'Guatemala City, Guatemala' 'Kanagawa' 'Klagenfurt'
 'Schoelcher' 'Merlo, Argentina' 'Melbourne Victoria, Australia']

#### Variável Ground

É possível concluir que na China, ainda não existiu nenhum torneio jogado em relva. 

Como não existem omissos nesta variável, o tratamento a fazer é aplicar o one hot encoder, para cada tipo de piso.

In [14]:
print(df['Ground'].unique())

['Hard' 'Clay' 'Carpet']

#### Variável Prize

In [15]:
print(df['Prize'].unique())

['$7,473,620' '$7,086,700' '$5,452,985' '$2,700,510' '$4,783,320'
 '$4,195,895' '$2,500,470' '$3,849,445' '$2,315,250' '$3,531,600'
 '$2,205,000' '$3,240,000' '$2,100,000' '$2,100,500' '$3,800,000' nan
 '$5,924,890' '$125,000' '$50,000' '$3,028,080' '$2,916,550' '$3,700,000'
 '$475,000' '$3,515,225' '$3,401,860' '$666,960' '$931,335' '$733,655'
 '$1,028,885' '$1,070,040' '$75,000' '$840,915' '$1,096,575' '$150,000'
 '$641,305' '$607,940' '$15,000' '$590,230' '$162,480' '$25,000' '$54,160'
 '$135,400' '$81,240' '$10,000' '$35,000' '$100,000' '$499,000' '$375,000'
 '$355,000' '$350,000' '$325,000' '$315,000' '$303,000' '$275,000'
 '$305,000' '$295,000']

In [16]:
df[df[['Prize']].isna().any(axis=1)]

,PlayerName,Born,Height,Hand,LinkPlayer,Tournament,Date,Ground,Prize,GameRound,GameRank,Oponent,WL,Score,Location
83,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,Beijing Olympics,2008.08.11 - 2008.08.17,Hard,NaN,Round of 16,22,Mikhail Youzhny,W,"76, 63",China
84,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,Beijing Olympics,2008.08.11 - 2008.08.17,Hard,NaN,Round of 32,35,Rainer Schuettler,W,64 62,China
85,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,Beijing Olympics,2008.08.11 - 2008.08.17,Hard,NaN,Round of 64,59,Robby Ginepri,W,64 64,China
86,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,Beijing Olympics,2008.08.11 - 2008.08.17,Hard,NaN,Semi-Finals,2,Rafael Nadal,L,46 61 46,China
87,Novak Djokovic,"Belgrade, Serbia",188.0,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/novak-djoko...,Beijing Olympics,2008.08.11 - 2008.08.17,Hard,NaN,Olympic Bronze,7,James Blake,W,63 76,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25899,David Agung Susanto,NaN,NaN,NaN,https://www.atptour.com/en/players/david-agung...,TPE vs. INA AOGI 2nd Rd. Play-Off,2013.09.09 - 2013.09.15,Hard,NaN,Round Robin,239,Ti Chen,L,36 46,China
26143,Hong Kit Wong,NaN,NaN,NaN,https://www.atptour.com/en/players/hong-kit-wo...,G2 BEN vs HKG Round 1,2022.02.28 - 2022.03.05,Hard,NaN,Round Robin,1881,Alexis Klegou,W,16 64 41 (RET),China
26210,Jeson Patrombon,NaN,NaN,"Right-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/jeson-patro...,TPE vs. PHI AOGII 2nd Rd.,2015.07.13 - 2015.07.19,Hard,NaN,Round Robin,667,Jui-Chen Hung,L,26 26 16,China
26276,Shahin Khaledan,NaN,NaN,NaN,https://www.atptour.com/en/players/shahin-khal...,TPE vs. IRN AOG2 Play-Off,2018.04.02 - 2018.04.08,Hard,NaN,Round Robin,1971,Yu Hsiou Hsu,L,64 16 8-10,China
26277,Shahin Khaledan,NaN,NaN,NaN,https://www.atptour.com/en/players/shahin-khal...,TPE vs. IRN AOG2 Play-Off,2018.04.02 - 2018.04.08,Hard,NaN,Round Robin,250,Tsung-Hua Yang,L,46 36,China

#### Variável Height

In [17]:
print(df['Height'].unique())

[188. 198. 185. 193. 196. 183. 170. 211. 191. 208. 175. 178. 180. 203.
 201. 173. 168.  nan 163. 165.   0.  15. 206.]

In [18]:
df[df[['Height']].isna().any(axis=1)]

,PlayerName,Born,Height,Hand,LinkPlayer,Tournament,Date,Ground,Prize,GameRound,GameRank,Oponent,WL,Score,Location
4309,Kaichi Uchida,NaN,NaN,"Right-Handed, Unknown Backhand",https://www.atptour.com/en/players/kaichi-uchi...,Shenzhen 2,2019.10.28 - 2019.11.03,Hard,"$135,400",Round of 64,257,Duckhee Lee,L,57 16,China
4310,Kaichi Uchida,NaN,NaN,"Right-Handed, Unknown Backhand",https://www.atptour.com/en/players/kaichi-uchi...,Ningbo,2019.10.14 - 2019.10.20,Hard,"$162,480",Round of 64,721,Fabien Reboul,W,26 75 63,China
4311,Kaichi Uchida,NaN,NaN,"Right-Handed, Unknown Backhand",https://www.atptour.com/en/players/kaichi-uchi...,Liuzhou,2019.10.21 - 2019.10.27,Hard,"$54,160",Round of 64,262,JiSung Nam,L,36 67,China
4312,Kaichi Uchida,NaN,NaN,"Right-Handed, Unknown Backhand",https://www.atptour.com/en/players/kaichi-uchi...,Ningbo,2019.10.14 - 2019.10.20,Hard,"$162,480",Round of 32,137,Tatsuma Ito,L,63 36 46,China
4313,Kaichi Uchida,NaN,NaN,"Right-Handed, Unknown Backhand",https://www.atptour.com/en/players/kaichi-uchi...,Jinan,2019.09.02 - 2019.09.08,Hard,"$162,480",Round of 64,263,Yunseong Chung,W,62 64,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26229,Jurence Zosimo Mendoza,NaN,NaN,"Left-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/jurence-zos...,M25 Qujing,2019.07.08 - 2019.07.14,Hard,"$25,000",Round of 32,-,Hanyi Liu,L,46 46,China
26230,Jurence Zosimo Mendoza,NaN,NaN,"Left-Handed, Two-Handed Backhand",https://www.atptour.com/en/players/jurence-zos...,M25 Kunshan,2019.07.01 - 2019.07.07,Hard,"$25,000",Round of 32,-,Haitong Xia,L,36 64 16,China
26259,Jin-Yen Chiang,NaN,NaN,"Right-Handed, Unknown Backhand",https://www.atptour.com/en/players/jinn-yen-ch...,Taipei,1993.04.26 - 1993.05.02,Hard,"$100,000",Round of 32,204,Gary Muller,L,06 67,China
26276,Shahin Khaledan,NaN,NaN,NaN,https://www.atptour.com/en/players/shahin-khal...,TPE vs. IRN AOG2 Play-Off,2018.04.02 - 2018.04.08,Hard,NaN,Round Robin,1971,Yu Hsiou Hsu,L,64 16 8-10,China
26277,Shahin Khaledan,NaN,NaN,NaN,https://www.atptour.com/en/players/shahin-khal...,TPE vs. IRN AOG2 Play-Off,2018.04.02 - 2018.04.08,Hard,NaN,Round Robin,250,Tsung-Hua Yang,L,46 36,China

#### Variável Hand

In [19]:
print(df['Hand'].unique())

['Right-Handed, Two-Handed Backhand' 'Left-Handed, Two-Handed Backhand'
 'Right-Handed, One-Handed Backhand' 'Left-Handed, One-Handed Backhand'
 'Right-Handed, Unknown Backhand' 'Left-Handed, Unknown Backhand' nan
 'Ambidextrous, Two-Handed Backhand']

In [20]:
df[df[['Hand']].isna().any(axis=1)]

,PlayerName,Born,Height,Hand,LinkPlayer,Tournament,Date,Ground,Prize,GameRound,GameRank,Oponent,WL,Score,Location
10700,Tsung-Hao Huang,NaN,NaN,NaN,https://www.atptour.com/en/players/tsung-hao-h...,M15 Nanchang,2019.09.30 - 2019.10.06,Clay,"$15,000",Round of 16,1019,N Vijay Sundar Prashanth,W,64 75,China
10701,Tsung-Hao Huang,NaN,NaN,NaN,https://www.atptour.com/en/players/tsung-hao-h...,M15 Nanchang,2019.09.30 - 2019.10.06,Clay,"$15,000",Quarter-Finals,1016,Chukang Wang,L,26 46,China
10702,Tsung-Hao Huang,NaN,NaN,NaN,https://www.atptour.com/en/players/tsung-hao-h...,M15 Nanchang,2019.09.30 - 2019.10.06,Clay,"$15,000",Round of 32,1162,Wei Qiang Zheng,W,62 62,China
10703,Tsung-Hao Huang,NaN,NaN,NaN,https://www.atptour.com/en/players/tsung-hao-h...,M15 Nanchang,2019.09.23 - 2019.09.29,Clay,"$15,000",Round of 16,1045,Chukang Wang,L,36 62 36,China
10704,Tsung-Hao Huang,NaN,NaN,NaN,https://www.atptour.com/en/players/tsung-hao-h...,M15 Nanchang,2019.09.23 - 2019.09.29,Clay,"$15,000",Round of 32,1851,Shohei Chikami,W,46 61 61,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26348,Sheng Hao Zhou,NaN,175.0,NaN,https://www.atptour.com/en/players/sheng-hao-z...,Nanchang,2014.06.23 - 2014.06.29,Hard,"$50,000",1st Round Qualifying,2099,Xiao Gong,L,46 36,China
26349,Sheng Hao Zhou,NaN,175.0,NaN,https://www.atptour.com/en/players/sheng-hao-z...,China F6,2014.06.02 - 2014.06.08,Hard,"$15,000",Round of 32,344,Nicolas Meister,L,26 06,China
26350,Sheng Hao Zhou,NaN,175.0,NaN,https://www.atptour.com/en/players/sheng-hao-z...,Shanghai1,2013.09.02 - 2013.09.08,Hard,"$50,000",2nd Round Qualifying,1274,He Feng,L,36 36,China
26351,Sheng Hao Zhou,NaN,175.0,NaN,https://www.atptour.com/en/players/sheng-hao-z...,China F7,2014.06.09 - 2014.06.15,Hard,"$15,000",Round of 32,1201,Xin Gao,L,06 16,China
26352,Sheng Hao Zhou,NaN,175.0,NaN,https://www.atptour.com/en/players/sheng-hao-z...,Shenzhen,2014.04.21 - 2014.04.27,Hard,"$50,000",1st Round Qualifying,1397,Hsien-Yin Peng,L,46 46,China

#### Variável GameRound

In [21]:
print(df['GameRound'].unique())

['Quarter-Finals' 'Round of 16' 'Round of 32' 'Round of 64' 'Finals'
 'Semi-Finals' 'Round Robin' 'Olympic Bronze' '3rd Round Qualifying'
 '1st Round Qualifying' '2nd Round Qualifying']

#### Variável Date

In [22]:
print(df['Date'].unique())

['2019.10.07 - 2019.10.13' '2018.10.08 - 2018.10.14'
 '2016.10.10 - 2016.10.16' '2015.10.05 - 2015.10.11'
 '2015.10.12 - 2015.10.18' '2014.10.06 - 2014.10.12'
 '2014.09.29 - 2014.10.05' '2013.10.07 - 2013.10.13'
 '2013.09.30 - 2013.10.06' '2012.10.08 - 2012.10.14'
 '2012.10.01 - 2012.10.07' '2010.10.11 - 2010.10.17'
 '2010.10.04 - 2010.10.10' '2009.10.12 - 2009.10.18'
 '2009.10.05 - 2009.10.11' '2008.11.10 - 2008.11.16'
 '2008.08.11 - 2008.08.17' '2007.11.12 - 2007.11.18'
 '2017.10.09 - 2017.10.15' '2015.09.21 - 2015.09.27'
 '2015.09.07 - 2015.09.13' '2015.09.14 - 2015.09.20'
 '2017.10.02 - 2017.10.08' '2016.10.03 - 2016.10.09'
 '2011.10.10 - 2011.10.16' '2006.11.13 - 2006.11.19'
 '2005.09.12 - 2005.09.18' '2019.09.30 - 2019.10.06'
 '2018.10.01 - 2018.10.07' '2017.09.25 - 2017.10.01'
 '2019.09.23 - 2019.09.29' '2018.09.24 - 2018.09.30'
 '2017.03.20 - 2017.03.25' '2017.03.13 - 2017.03.19'
 '2016.09.26 - 2016.10.02' '2017.04.24 - 2017.04.30'
 '2017.04.17 - 2017.04.23' '2018.10.15 - 2018.10.21'
 '2018.03.19 - 2018.03.25' '2018.03.12 - 2018.03.18'
 '2018.03.05 - 2018.03.11' '2017.10.30 - 2017.11.05'
 '2017.10.23 - 2017.10.29' '2017.10.16 - 2017.10.22'
 '2016.03.21 - 2016.03.27' '2016.03.14 - 2016.03.20'
 '2016.03.07 - 2016.03.13' '2017.03.06 - 2017.03.12'
 '2015.09.28 - 2015.10.04' '2011.10.03 - 2011.10.09'
 '2007.09.10 - 2007.09.16' '2018.09.17 - 2018.09.23'
 '2014.08.25 - 2014.08.31' '2005.11.14 - 2005.11.20'
 '2002.11.11 - 2002.11.17' '2016.04.25 - 2016.05.01'
 '2011.04.18 - 2011.04.24' '2011.04.11 - 2011.04.17'
 '2018.09.10 - 2018.09.16' '2018.09.03 - 2018.09.09'
 '2018.08.06 - 2018.08.12' '2018.07.30 - 2018.08.05'
 '2014.09.22 - 2014.09.28' '2014.04.14 - 2014.04.20'
 '2014.04.07 - 2014.04.13' '2019.04.08 - 2019.04.14'
 '2018.04.23 - 2018.04.29' '2018.04.16 - 2018.04.22'
 '2018.04.09 - 2018.04.15' '2016.09.05 - 2016.09.12'
 '2018.10.22 - 2018.10.28' '2018.10.29 - 2018.11.04'
 '2017.08.07 - 2017.08.12' '2017.07.31 - 2017.08.06'
 '2017.09.11 - 2017.09.17' '2017.05.29 - 2017.06.04'
 '2017.05.22 - 2017.05.28' '2017.05.15 - 2017.05.21'
 '2015.04.27 - 2015.05.03' '2015.03.16 - 2015.03.22'
 '2015.03.09 - 2015.03.15' '2013.05.06 - 2013.05.12'
 '2013.04.29 - 2013.05.05' '2013.04.22 - 2013.04.28'
 '2013.04.15 - 2013.04.21' '2011.01.17 - 2011.01.23'
 '2019.09.02 - 2019.09.08' '2019.08.26 - 2019.09.01'
 '2019.07.29 - 2019.08.04' '2019.04.22 - 2019.04.28'
 '2019.04.15 - 2019.04.21' '2019.03.18 - 2019.03.24'
 '2019.03.11 - 2019.03.17' '2016.05.09 - 2016.05.15'
 '2015.10.19 - 2015.10.25' '2014.09.01 - 2014.09.07'
 '2019.10.28 - 2019.11.03' '2019.09.09 - 2019.09.14'
 '2016.10.24 - 2016.10.30' '2016.10.17 - 2016.10.23'
 '2016.09.19 - 2016.09.25' '2016.08.08 - 2016.08.14'
 '2016.08.01 - 2016.08.07' '2016.05.23 - 2016.05.29'
 '2016.05.16 - 2016.05.22' '2017.12.18 - 2017.12.24'
 '2011.03.21 - 2011.03.27' '2011.03.14 - 2011.03.20'
 '2014.04.28 - 2014.05.04' '2012.09.10 - 2012.09.16'
 '2012.09.03 - 2012.09.09' '2012.04.16 - 2012.04.22'
 '2012.04.23 - 2012.04.29' '2012.04.09 - 2012.04.15'
 '2019.03.04 - 2019.03.10' '2012.01.02 - 2012.01.08'
 '2016.09.12 - 2016.09.17' '2016.04.18 - 2016.04.24'
 '2014.04.28 - 2014.05.03' '2014.04.21 - 2014.04.27'
 '2008.09.22 - 2008.09.28' '2017.09.04 - 2017.09.10'
 '2019.01.28 - 2019.02.02' '2014.07.14 - 2014.07.20'
 '2015.10.26 - 2015.11.01' '2013.04.08 - 2013.04.14'
 '2012.02.13 - 2012.02.19' '2012.02.06 - 2012.02.12'
 '2006.09.11 - 2006.09.17' '2002.09.23 - 2002.09.29'
 '2014.03.10 - 2014.03.16' '2014.03.03 - 2014.03.09'
 '2014.02.24 - 2014.03.02' '2003.09.22 - 2003.09.28'
 '2017.07.24 - 2017.07.30' '2014.07.21 - 2014.07.27'
 '2012.07.30 - 2012.08.05' '2012.07.23 - 2012.07.29'
 '2012.07.16 - 2012.07.22' '2012.01.09 - 2012.01.15'
 '2004.09.20 - 2004.09.26' '2019.10.21 - 2019.10.27'
 '2013.09.16 - 2013.09.22' '2019.10.14 - 2019.10.20'
 '2018.07.23 - 2018.07.29' '2018.07.16 - 2018.07.22'
 '2016.12.26 - 2017.01.01' '2010.05.03 - 2010.05.09'
 '2009.02.02 - 2009.02.08' '2016.05.30 - 2016.06.05'
 '2019.09.09 - 2019.09.15' '2016.12.19 - 2016.12.25'
 '2018.04.02 - 2018.04.08' '2014.08.18 - 2014.08.24'
 '2017.02.27 - 2017.03.05' '2017.02.20 - 2017.02.26'
 '2017.02.13 - 2017.02.19' '2014.06.23 - 2014.06.29'
 '2014.06.02 - 2014.06.08' '2014.06.16 - 2014.06.22'
 '2013.05.20 - 2013.05.26' '2013.05.13 - 2013.05.19'
 '2011.09.12 - 2011.09.18' '2011.09.05 - 2011.09.11'
 '2004.09.13 - 2004.09.19' '2013.09.02 - 2013.09.08'
 '2007.10.08 - 2007.10.14' '2007.02.05 - 2007.02.11'
 '2017.07.03 - 2017.07.09' '2017.06.26 - 2017.07.02'
 '2014.03.17 - 2014.03.23' '2013.08.19 - 2013.08.25'
 '2011.07.11 - 2011.07.17' '2013.07.08 - 2013.07.14'
 '2012.03.12 - 2012.03.18' '2011.08.01 - 2011.08.07'
 '2011.07.25 - 2011.07.31' '2008.01.28 - 2008.02.03'
 '2006.02.27 - 2006.03.12' '2008.01.21 - 2008.01.27'
 '2010.08.02 - 2010.08.08' '2009.08.10 - 2009.08.16'
 '2009.08.03 - 2009.08.09' '2017.06.19 - 2017.06.25'
 '2017.06.12 - 2017.06.18' '2016.04.11 - 2016.04.17'
 '2016.04.04 - 2016.04.10' '2014.06.09 - 2014.06.15'
 '2014.03.31 - 2014.04.06' '2010.03.01 - 2010.03.07'
 '2004.11.22 - 2004.11.28' '2004.11.15 - 2004.11.21'
 '2018.01.22 - 2018.01.28' '2018.01.15 - 2018.01.21'
 '2018.07.09 - 2018.07.15' '2018.07.02 - 2018.07.08'
 '2017.07.10 - 2017.07.16' '2015.08.17 - 2015.08.23'
 '2013.08.26 - 2013.09.01' '2008.01.14 - 2008.01.20'
 '2017.07.17 - 2017.07.23' '2017.05.08 - 2017.05.14'
 '2017.04.10 - 2017.04.16' '2011.07.04 - 2011.07.10'
 '2016.02.29 - 2016.03.06' '2016.02.22 - 2016.02.28'
 '2016.02.15 - 2016.02.21' '2010.03.15 - 2010.03.28'
 '2008.04.14 - 2008.04.20' '2008.04.21 - 2008.04.27'
 '2015.06.01 - 2015.06.07' '2015.05.18 - 2015.05.24'
 '2015.05.25 - 2015.05.31' '2006.01.09 - 2006.01.22'
 '2006.01.16 - 2006.01.22' '2019.07.22 - 2019.07.28'
 '2019.07.15 - 2019.07.21' '2019.06.10 - 2019.06.16'
 '2019.05.13 - 2019.05.19' '2019.05.06 - 2019.05.12'
 '2015.08.24 - 2015.08.30' '2013.01.28 - 2013.02.03'
 '2007.05.21 - 2007.06.03' '2007.05.14 - 2007.05.20'
 '2007.05.07 - 2007.05.13' '2018.05.28 - 2018.06.03'
 '2015.04.06 - 2015.04.12' '2015.04.13 - 2015.04.19'
 '2017.04.03 - 2017.04.09' '2016.07.18 - 2016.07.24'
 '2016.06.27 - 2016.07.03' '2015.08.10 - 2015.08.16'
 '2015.08.03 - 2015.08.09' '2013.08.12 - 2013.08.18'
 '2019.07.08 - 2019.07.14' '2019.06.24 - 2019.06.30'
 '2019.06.17 - 2019.06.23' '2019.05.27 - 2019.06.02'
 '2019.01.14 - 2019.01.20' '2018.08.20 - 2018.08.26'
 '2018.04.30 - 2018.05.06' '2018.01.08 - 2018.01.14'
 '2015.07.20 - 2015.07.26' '2015.07.13 - 2015.07.19'
 '2015.06.29 - 2015.07.05' '2015.06.22 - 2015.06.28'
 '2015.04.20 - 2015.04.26' '2015.03.30 - 2015.04.05'
 '2012.06.25 - 2012.07.01' '2012.05.14 - 2012.05.20'
 '2012.06.18 - 2012.06.24' '2012.05.21 - 2012.05.27'
 '2010.09.27 - 2010.10.03' '2010.09.20 - 2010.09.26'
 '2009.05.11 - 2009.05.17' '2009.05.04 - 2009.05.10'
 '2009.01.12 - 2009.01.25' '2009.01.05 - 2009.01.11'
 '2007.11.19 - 2007.11.25' '2007.06.25 - 2007.07.01'
 '2006.03.13 - 2006.03.26' '2006.03.06 - 2006.03.12'
 '2019.04.29 - 2019.05.05' '2019.07.01 - 2019.07.07'
 '2013.08.05 - 2013.08.11' '2011.11.14 - 2011.11.20'
 '2011.06.13 - 2011.06.19' '2011.06.06 - 2011.06.12'
 '2018.05.14 - 2018.05.20' '2018.05.07 - 2018.05.13'
 '2004.09.27 - 2004.10.03' '2014.09.08 - 2014.09.14'
 '2010.05.31 - 2010.06.13' '2018.08.27 - 2018.09.02'
 '2018.08.13 - 2018.08.19' '2015.03.02 - 2015.03.08'
 '2011.02.28 - 2011.03.06' '2009.03.02 - 2009.03.08'
 '2008.02.04 - 2008.02.10' '2007.04.02 - 2007.04.08'
 '2003.09.15 - 2003.09.21' '2003.04.14 - 2003.04.20'
 '2003.03.31 - 2003.04.13' '2003.02.03 - 2003.02.09'
 '2002.04.22 - 2002.04.28' '2002.04.15 - 2002.04.21'
 '2001.08.06 - 2001.08.12' '2001.07.30 - 2001.08.05'
 '2018.06.04 - 2018.06.10' '2011.01.10 - 2011.01.16'
 '2010.06.07 - 2010.06.13' '2010.04.12 - 2010.04.25'
 '2010.04.05 - 2010.04.18' '2010.03.22 - 2010.03.28'
 '2009.08.17 - 2009.08.23' '2007.10.15 - 2007.10.21'
 '2007.06.18 - 2007.07.01' '2005.07.25 - 2005.07.31'
 '2005.11.07 - 2005.11.13' '2005.05.23 - 2005.05.29'
 '2005.05.16 - 2005.05.29' '2004.11.08 - 2004.11.14'
 '2005.07.18 - 2005.07.24' '2019.09.16 - 2019.09.22'
 '2013.04.01 - 2013.04.07' '2012.04.02 - 2012.04.08'
 '2010.07.05 - 2010.07.11' '2016.07.11 - 2016.07.17'
 '2016.07.04 - 2016.07.10' '2018.12.31 - 2019.01.06'
 '2019.01.07 - 2019.01.13' '2018.01.29 - 2018.02.04'
 '2014.01.27 - 2014.02.02' '2011.05.16 - 2011.05.22'
 '2011.05.09 - 2011.05.15' '2009.09.14 - 2009.09.20'
 '2022.02.28 - 2022.03.05' '2013.09.09 - 2013.09.15'
 '2011.11.07 - 2011.11.13' '2006.02.06 - 2006.02.12'
 '2006.04.03 - 2006.04.09' '2004.02.02 - 2004.02.08'
 '2003.11.24 - 2003.11.30' '2003.04.21 - 2003.04.27'
 '2006.09.18 - 2006.09.24' '2000.10.16 - 2000.10.22'
 '2001.05.07 - 2001.05.13' '2001.04.30 - 2001.05.06'
 '2005.05.30 - 2005.06.05' '2004.04.05 - 2004.04.11'
 '2001.09.24 - 2001.09.30' '2001.09.17 - 2001.09.23'
 '2000.04.03 - 2000.04.09' '1999.05.10 - 1999.05.16'
 '1999.05.03 - 1999.05.09' '1998.05.04 - 1998.05.10'
 '2002.08.19 - 2002.09.01' '2002.08.26 - 2002.09.01'
 '2000.05.01 - 2000.05.07' '2000.04.24 - 2000.04.30'
 '2000.10.02 - 2000.10.08' '1999.10.04 - 1999.10.10'
 '1998.05.11 - 1998.05.17' '1997.03.31 - 1997.04.06'
 '1996.09.23 - 1996.09.29' '2002.02.04 - 2002.02.17'
 '1998.10.05 - 1998.10.11' '1997.09.29 - 1997.10.05'
 '1995.10.16 - 1995.10.22' '2005.07.11 - 2005.07.17'
 '1996.10.07 - 1996.10.13' '1993.10.18 - 1993.10.24'
 '1993.04.26 - 1993.05.02' '1997.01.27 - 1997.02.02'
 '2003.02.10 - 2003.02.23' '1994.10.17 - 1994.10.23'
 '1992.12.07 - 1992.12.13' '1999.02.08 - 1999.02.14'
 '2001.02.05 - 2001.02.11' '2000.01.31 - 2000.02.06'
 '1996.01.29 - 1996.02.04' '1995.11.06 - 1995.11.12'
 '1992.04.27 - 1992.05.03' '1994.04.25 - 1994.05.01'
 '1997.02.03 - 1997.02.09' '1989.10.30 - 1989.11.05'
 '1988.11.07 - 1988.11.13' '1991.04.15 - 1991.04.21'
 '1994.01.31 - 1994.02.06' '1990.04.30 - 1990.05.06'
 '1982.11.08 - 1982.11.14' '1983.11.07' '1981.11.09' '1980.11.10'
 '1979.11.12 - 1979.11.18' '1977.11.21 - 1977.11.26'
 '1984.10.29 - 1984.11.05' '1980.10.13' '1978.11.13 - 1978.11.19'
 '1987.09.28 - 1987.10.04']

### Verificação de Duplicados


Em baixo, é possível verificar que existem 8 duplicados na base de dados. 

Estas observações deverão ser eliminadas.

In [23]:
duplicates = df[df.duplicated()]
print(duplicates)

           PlayerName              Born  Height  \
1372     David Goffin  Rocourt, Belgium   180.0
1373     David Goffin  Rocourt, Belgium   180.0
1374     David Goffin  Rocourt, Belgium   180.0
26259  Jin-Yen Chiang               NaN     NaN
26353     Pedro Sousa  Lisbon, Portugal   180.0
26354     Pedro Sousa  Lisbon, Portugal   180.0
26355     Pedro Sousa  Lisbon, Portugal   180.0
26356     Pedro Sousa  Lisbon, Portugal   180.0

                                    Hand  \
1372   Right-Handed, Two-Handed Backhand
1373   Right-Handed, Two-Handed Backhand
1374   Right-Handed, Two-Handed Backhand
26259     Right-Handed, Unknown Backhand
26353  Right-Handed, Two-Handed Backhand
26354  Right-Handed, Two-Handed Backhand
26355  Right-Handed, Two-Handed Backhand
26356  Right-Handed, Two-Handed Backhand

                                              LinkPlayer  \
1372   https://www.atptour.com/en/players/david-goffi...
1373   https://www.atptour.com/en/players/david-goffi...
1374   https://www.atptour.com/en/players/david-goffi...
26259  https://www.atptour.com/en/players/jinn-yen-ch...
26353  https://www.atptour.com/en/players/pedro-sousa...
26354  https://www.atptour.com/en/players/pedro-sousa...
26355  https://www.atptour.com/en/players/pedro-sousa...
26356  https://www.atptour.com/en/players/pedro-sousa...

                      Tournament                     Date Ground       Prize  \
1372   ATP Masters 1000 Shanghai  2019.10.07 - 2019.10.13   Hard  $7,473,620
1373   ATP Masters 1000 Shanghai  2019.10.07 - 2019.10.13   Hard  $7,473,620
1374   ATP Masters 1000 Shanghai  2019.10.07 - 2019.10.13   Hard  $7,473,620
26259                     Taipei  1993.04.26 - 1993.05.02   Hard    $100,000
26353                     Zhuhai  2017.03.06 - 2017.03.12   Hard     $50,000
26354                   Quanzhou  2017.03.20 - 2017.03.25   Hard     $50,000
26355                   Quanzhou  2017.03.20 - 2017.03.25   Hard     $50,000
26356                   Shenzhen  2017.03.13 - 2017.03.19   Hard     $75,000

         GameRound GameRank               Oponent WL        Score Location
1372   Round of 16        3         Roger Federer  L      67,  46    China
1373   Round of 32       57     Mikhail Kukushkin  W  62 30 (RET)    China
1374   Round of 64       52       Richard Gasquet  W        62 63    China
26259  Round of 32      204           Gary Muller  L        06 67    China
26353  Round of 32      147           Blaz Kavcic  L        36 36    China
26354  Round of 32      576               Yan Bai  W        64 62    China
26355  Round of 16      338     Matteo Berrettini  L   46 76,  26    China
26356  Round of 32      186  Aleksandr Nedovyesov  L        46 06    China